apiVersion: v1 
kind: Service
metadata:
  name: frontendservice
spec:
  selector:
    app: frontend
    # chon bayad az jahane biroon ghabele dastresi bashe az loadbalancer estefade mikonim``
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
