apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: farbodgerami/kubedemotasks:latest
          env:
            - name: AUTHADDRESS
              value: "authsservice.default"
            - name: TASKS_FOLDER 
              value: tasks
            
    


 